name: Wingify Engineering
description: This is the engineering blog from the hackers at Wingify
keywords: wingify, ab testing, split testing

pygments:    true
safe:        true
timezone:    Asia/Kolkata
future:      true
permalink:   /posts/:title/
paginate:    5
